export const LEADERS = [
  "Ada Lovelace",
  "Amina",
  "Ashoka World Conqueror",
  "Ashoka World Renouncer",
  "Augustus",
  "Benjamin Franklin",
  "Catherine the Great",
  "Charlemagne",
  "Confucius",
  "Friedrich Baroque",
  "Friedrich Oblique",
  "Genghis Khan",
  "Harriet Tubman",
  "Hatshepsut",
  "Himiko High Shaman",
  "Himiko Queen of Wa",
  "Ibn Battuta",
  "Isabella",
  "José Rizal",
  "Lafayette",
  "Lakshmibai",
  "Machiavelli",
  "Napoleon Emperor",
  "Napoleon Revolutionary",
  "Pachacuti",
  "Simón Bolívar",
  "Tecumseh",
  "Trung Trac",
  "Xerxes King of Kings",
  "Xerxes the Achaemenid",
];

export const CIVILIZATIONS = [
  "Aksumite",
  "Assyrian",
  "Carthaginian",
  "Egyptian",
  "Greek",
  "Han",
  "Khmer",
  "Mauryan",
  "Maya",
  "Mississippian",
  "Persian",
  "Roman",
  "Silla",
];

export const DEFAULT_LEADERS = [
  //"Ada Lovelace",
  "Amina",
  //"Ashoka World Conqueror",
  "Ashoka World Renouncer",
  "Augustus",
  "Benjamin Franklin",
  "Catherine the Great",
  "Charlemagne",
  "Confucius",
  //"Friedrich Baroque",
  "Friedrich Oblique",
  //"Genghis Khan",
  "Harriet Tubman",
  "Hatshepsut",
  //"Himiko High Shaman",
  "Himiko Queen of Wa",
  "Ibn Battuta",
  "Isabella",
  "José Rizal",
  "Lafayette",
  //"Lakshmibai",
  "Machiavelli",
  "Napoleon Emperor",
  "Napoleon Revolutionary",
  "Pachacuti",
  //"Simón Bolívar",
  //"Tecumseh",
  "Trung Trac",
  "Xerxes King of Kings",
  //"Xerxes the Achaemenid",
];

export const DEFAULT_CIVILIZATIONS = [
  "Aksumite",
  //"Assyrian",
  //"Carthaginian",
  "Egyptian",
  "Greek",
  "Han",
  "Khmer",
  "Mauryan",
  "Maya",
  "Mississippian",
  "Persian",
  "Roman",
  //"Silla",
];
